### PR TITLE
Converted to Cocoapods

### PR DESCRIPTION
**Pull request by Sajjon**
This PR makes repo build on clone, using Cocoapods, nstead of Carthage which feels a bit outdated.

The `Pods` folder is included in git as it should.

Coming PR will make use of SwiftLint.

### CODE REVIEW

**Comment by Sajjon** [comment]
The test `testTransactionOutput` is failing, strange because the response dictionary contains `result`

**Comment by saltyskip** [comment]
one of the fields is null which is currently not covered by the parsing, it needs to be fixed

**Comment by saltyskip** [comment]
We should not include Pod Frameworks into the project itself, we can keep a Podfile and a Podfile.lock and it should be on the onus of the downloader of the project to install the associated frameworks on their machine. 

Gemfile should not be included, it is not a requirement to use cocoapods for installation. We need to remain dependency manager agnostic (carthage and SPM will be supported in the future as well). 

You are free to add a contributors file and add your name to it, but the main authors have put significant time and work into developing this framework. If you show consistent time and effort we will be happy to put you as a main author. 

For any directory structure changes please let me know why the changes were necessary. As it stands the first step towards getting this PR merged in would be to remove the Pods directory so it's managed solely by the user and not on this repo

**Comment by saltyskip** [comment]
Closing this PR since it has become outdated since #24

**Pull request closed without merging**
